### ISSUE TITLE
Saving project does not automatically append extension 

### ISSUE THREAD

**Issue by brianng0305** [jveitchmichaelis/deeplabel#11]
System: Ubuntu 18.04, qt5, sqlite3

Sir, 
Thank you for your answer yesterday. May you please help to solve/answer the aformentioned question? I cannot find the database save file on the qt5 load-file window.

Please find the below picture for your reference. (qt5 window show nothing but my ubuntu window show the file I saved.)
[photo link](https://imgur.com/IY4VzNV)

Thank you.

**Comment by jveitchmichaelis** [comment]
Possibly a bug where saving doesn't append the extension. Try manually adding ".lbldb" to it and see if that works?

**Comment by brianng0305** [comment]
Sir,

Yes. It works. Thank you very much.

**Comment by jveitchmichaelis** [comment]
Fixed in https://github.com/jveitchmichaelis/deeplabel/commit/000578d6030d013194aea0736aa6b8c022ea15dd

also updated in https://github.com/jveitchmichaelis/deeplabel/commit/cfa61ea7e60ae269d7cede93f06d09b8ff074bda
