### ISSUE TITLE
how to use 

### ISSUE THREAD

**Issue by rockyzhengwu** [jveitchmichaelis/deeplabel#15]
I use Mac and I don't know how to label on image 

<img width="960" alt="截屏2020-06-04 上午11 49 43" src="https://user-images.githubusercontent.com/10402091/83713181-05a22000-a65a-11ea-97d7-51f305cff427.png">

**Comment by jveitchmichaelis** [comment]
Click the annotate (square) button, right of the arrows. Then click once to start the box, once to end it, then space to commit.

**Comment by rockyzhengwu** [comment]
do you mean this button in red circle ?
i click it but nothing happen and i create a square on the text , but how to save it 
<img width="957" alt="截屏2020-06-04 下午12 56 55" src="https://user-images.githubusercontent.com/10402091/83716729-46eafd80-a663-11ea-9193-ff84db00d030.png">

**Comment by jveitchmichaelis** [comment]
Yes, once you've clicked twice to define the box (eg top left, bottom right corner), press space to save it. The reason nothing happens is that it's a mode. The button next to it (the hand) activates selection mode, so you can click to select labels in case you need to delete them. 

If you're drawing a box and make a mistake, you can also press Escape to cancel.
