### ISSUE TITLE
"Jump to image" button need repaint ImageDisplay on OS X

### ISSUE THREAD

**Issue by rockyzhengwu** [jveitchmichaelis/deeplabel#16]
<img width="967" alt="截屏2020-06-06 下午4 16 19" src="https://user-images.githubusercontent.com/10402091/83939679-69227e00-a811-11ea-80d0-6d119868e71f.png">

update the number and click the button nothing happen , but if  I switch to other window like chrome it display well.
I think should repaint or update , i add repaint() add at the end of function ```void ImageDisplay::updateDisplay()``` it work . 

it's too simple to fix , i didn't make a PR.

**Comment by jveitchmichaelis** [comment]
I can't replicate this on Linux - it repaints immediately for me. I'll have a look, thanks.

**Comment by jveitchmichaelis** [comment]
Thanks for the report! 

https://github.com/jveitchmichaelis/deeplabel/commit/d06781ea68b8719d2eb1f1918726e54969e40c7f
