### ISSUE TITLE
Add support for calling external darknet

### ISSUE THREAD

**Issue by jveitchmichaelis** [jveitchmichaelis/deeplabel#18]
As per this issue, it would be nice if we could support Yolov4, but currently we rely on opencv for backend processing. We could, alternatively, ask the user to provide a darknet binary/dll and use that.

This would also open the door for simple integration of training into the deeplabel GUI.

https://github.com/jveitchmichaelis/deeplabel/issues/17

**Comment by brianng0305** [comment]
Sir, opencv 4.4 was released yesterday. It supports yolov4. I am going to install it.

**Comment by jveitchmichaelis** [comment]
Great, let me know if it works!

**Comment by brianng0305** [comment]
Sir, Opencv can run yolov4 and yolo-tiny4.
But I use deeplabel to detect no bounding box appear.


I tried to re-install the deeplabel, it showed:

In file included from src/mainwindow.h:24:0,
                 from src/mainwindow.cpp:1:
src/detection/detectoropencv.h:11:9: fatal error: opencv2/dnn.hpp: No such file or directory
 #include<opencv2/dnn.hpp>
         ^~~~~~~~~~~~~~~~~
In file included from src/mainwindow.h:24:0,
                 from src/main.cpp:1:
src/detection/detectoropencv.h:11:9: fatal error: opencv2/dnn.hpp: No such file or directory
 #include<opencv2/dnn.hpp>
         ^~~~~~~~~~~~~~~~~

**Comment by jveitchmichaelis** [comment]
It may have moved in 4.4, try replacing with `#include <opencv2/dnn/dnn.hpp>`

**Comment by brianng0305** [comment]
> It may have moved in 4.4, try replacing with `#include <opencv2/dnn/dnn.hpp>`

Sorry. The reason of mentioned failure is I forgot to set path in Deeplabel.pro.

The file path is still opencv2/dnn/dnn.hpp on anaconda environment.

but make is still error:

/usr/bin/ld: cannot find -lopencv_tracking
/usr/bin/ld: cannot find -lopencv_dnn
collect2: error: ld returned 1 exit status
Makefile:262: recipe for target 'release/DeepLabel' failed
make: *** [release/DeepLabel] Error 1

**Comment by jveitchmichaelis** [comment]
Hmm ok so linker error - you're just missing the libs. Did you build those? (tracking requires contrib)

**Comment by brianng0305** [comment]
> Hmm ok so linker error - you're just missing the libs. Did you build those? (tracking requires contrib)

Yes. You are correct. Now I go to fix it. Thank you.

**Comment by jveitchmichaelis** [comment]
@brianng0305 did it work? :)

**Comment by brianng0305** [comment]
> @brianng0305 did it work? :)

Due to installed old version Deeplabel can run yolov4 so I gave up to install. Thanks.
