### ISSUE TITLE
Propogate Tracking Feature seg faults

### ISSUE THREAD

**Issue by shashank2408** [jveitchmichaelis/deeplabel#2]
I am currently labeling few images to retrain YOLO. I want to make use of the tracking feature. Here are the steps that I followed 
1. Label first image with a class and init tracking 
2. Check options "Propagate label to next image" ,"refine boxes after tracking" and try to propagate tracking. 

Observed Behaviour
 App closes Due to segmentation faults

Console output: Segmentation fault (core dumped)

There are no other debug messages that are printed

**Comment by jveitchmichaelis** [comment]
Does it work without refinement? That functionality is a bit buggy at the moment.

**Comment by shashank2408** [comment]
No it does not work even if refinement is unchecked. 
Here is one more observation
1. The first time I hit propagate, nothing happens. No objects are tracked or labelled 
2. Second time I hit propagate, I see a segmentation fault 
Hope this helps

**Comment by jveitchmichaelis** [comment]
OK, I'll take a look. It's possible that tracking has failed and it's not being caught properly.

If you can provide a couple of representative frames that crash, that'd be useful.

By the way, if you've enabled automatic label propagation then you shouldn't need to click the button too.

Update - I can't replicate this with data here, I've tried with eg no label in the first image, mashing the buttons in the second image, etc.

Is there anything unusual about your data?

**Comment by jveitchmichaelis** [comment]
I've possibly found a fix for this (https://github.com/jveitchmichaelis/deeplabel/commit/ef5530e59cb2369b6400e91c24d43f2ee5c7037b).

Other users reported a similar crash and I traced it to zero area bounding boxes (e.g. a QRect at (0,0) with height and width zero), which can be created sometimes (not sure where, this is obviously a bug). Trying to propagate these bounding boxes causes stuff to crash without any information.

It would be worth checking your images to see if you have more labels than you expect (e.g. two boxes, but the GUI says there are three).
