### ISSUE TITLE
issue with building on ubuntu 18.04

### ISSUE THREAD

**Issue by sa7ina** [jveitchmichaelis/deeplabel#20]
Hi

when i try building i get `qmake: could not find a Qt installation of ''`
what does it mean?
how can i fix it?

10x for the great tool.

**Comment by jveitchmichaelis** [comment]
Odd, do you have Qt installed? (if so, how did you install it/what version)

**Comment by sa7ina** [comment]
Ok
My bad.
I thought if i had qtcreator installed that's enough.
apt installed qt5-default.
but now i get: 
`Project MESSAGE: Linux
Cannot read /home/ei8ht/deeplabel/QtAwesome/QtAwesome/QtAwesome.pri: No such file or directory
`
10x for your help!

edit:
When i open the project in qtcreator it says:
`/deeplabel/src/imagedisplay.h:10:10: fatal error: QtAwesome.h: No such file or directory
 #include <QtAwesome.h>`

The folder QtAwesome is really empty.

**Comment by sa7ina** [comment]
Solved this one too.

Cloned `https://github.com/gamecreature/QtAwesome.git` in deeplabel dir and it worked.

Issue solved.
10X again!

**Comment by jveitchmichaelis** [comment]
It's a submodule, so you need to run `git submodule update --init --recursive` :)

If you get everything to compile, please close the issue, thanks!

**Comment by sa7ina** [comment]
OK
Did not know that.
:)
