### ISSUE TITLE
Command line interface

### ISSUE THREAD

**Issue by marcfielding1** [jveitchmichaelis/deeplabel#21]
Heya,

LOVE this, good work - quick question can we use this from the command line with the following use case:

We have items such as tin cans on a turntable when our setup has finished taking a video of it we'd like to fire it at our backend services, now we'd like to automatically label it via a bash script. So we'd probably confirm the first frame label and then look to track it across the rest since it's on a turntable it won't move much.

OR

We'd use automatic object detection via our own model in the right format.

Thanks

Marc

**Comment by jveitchmichaelis** [comment]
Hmm if you just want to do detection via command line there are probably better tools to use (e.g. whatever framework your model is trained in). Essentially all deeplabel is doing in this case is wrapping around OpenCV's DNN library - ditto for tracking.

I guess in theory this is possible, if you passed in either a image/video path + a model, we could have deeplabel load it, detect objects, start tracking and then repeat for the rest of the frames. But it might get a bit complex e.g. do you just want to detect for the first frame only and then track through the rest? At that point you might as well just run the detector every frame.

What would you expect the output from the CLI to be - a list of bounding boxes?

**Comment by jveitchmichaelis** [comment]
>We'd use automatic object detection via our own model in the right format.

CLI implemented in https://github.com/jveitchmichaelis/deeplabel/commit/c7634ac5fa0ecaa2c3be32afc770bb7da5832d16
