### ISSUE TITLE
OpenCV 4.0.0 does not have COLORMAP_MAGMA what is the right version?

### ISSUE THREAD

**Issue by tbhunderbird** [jveitchmichaelis/deeplabel#23]

**Comment by jveitchmichaelis** [comment]
You can see supported versions here. Looks like 4.1.0 at least:

https://docs.opencv.org/4.1.0/d3/d50/group__imgproc__colormap.html

**Comment by tbhunderbird** [comment]
It was meant as a hint to update your installation hints ;)
But thanks for the quick reply!

**Comment by jveitchmichaelis** [comment]
Haha updated!

https://github.com/jveitchmichaelis/deeplabel/commit/5ecd3da2f9865077330636c547b00ff4c263bb13
