### ISSUE TITLE
Segmentation Fault when creating new Project on Ubuntu 20.04 OpenCV 4.2.0 QT5

### ISSUE THREAD

**Issue by jlong23** [jveitchmichaelis/deeplabel#24]
blackberry:~/dev/deeplabel/release$ ./DeepLabel 
Database structure looks good
QSqlDatabasePrivate::removeDatabase: connection '/home/jlong/dev/fuzzy/bunny' is still in use, all queries will cease to work.
QSqlDatabasePrivate::addDatabase: duplicate connection name '/home/jlong/dev/fuzzy/bunny', old connection removed.
Database structure looks good
Segmentation fault (core dumped)

[bunny.zip](https://github.com/jveitchmichaelis/deeplabel/files/6110826/bunny.zip)

**Comment by jveitchmichaelis** [comment]
Can you provide some representative images that cause the crash/tell me a bit more about what you did before you got the segfault? The label database you've uploaded is empty and I can't replicate the error by opening it. Thanks!

**Comment by jveitchmichaelis** [comment]
Closing as no response in 5 months.
