### ISSUE TITLE
Resize/move existing/detected annotations

### ISSUE THREAD

**Issue by lukaswozniak** [jveitchmichaelis/deeplabel#29]
Is there any way to more/resize annotation?
Currently the only way I found working is to remove annotation and add it again with corrected position and size.
After running detector I find that many annotations are slightly inaccurate, and having easy way of correcting them would be a life saver.

**Comment by jveitchmichaelis** [comment]
@lukaswozniak  Tentatively added in https://github.com/jveitchmichaelis/deeplabel/commit/156092c777445a97696547dbb8f1469368cfeae7

![image](https://user-images.githubusercontent.com/3159591/135749983-93d2e477-c7e7-4cec-971f-eebcbc3220c1.png)

Give it a go! Hit the "select" icon and it should be obvious.

**Comment by lukaswozniak** [comment]
Awesome work man! Having a blast with it so far

**Comment by jveitchmichaelis** [comment]
Cool, let me know if you find any bugs. The only thing I thought of immediately was preventing dragging boxes beyond the extent of the window, but the bounding box values should be clamped on export anyway.

**Comment by lukaswozniak** [comment]
Well dragging the box out of the window is not something any user would want to do :) The only thing I've noticed so far is that if the boxes are overlapping then not always the selected one is prioritised.

**Comment by lukaswozniak** [comment]
For example:
![image](https://user-images.githubusercontent.com/43893492/135763256-27b83e28-bb89-4122-995b-f1187d965161.png)

Here I'm trying to resize the smaller one, but the program is all confused and moves the bigger one, even though it colored the smaller corner

**Comment by jveitchmichaelis** [comment]
Hmm overlapping boxes is an awkward, but common, case.

I think one easy fix would be to add a Z-Order to each box and then give
you the ability to adjust how the boxes stack on top of each other. I can
also add a check so that if you select something like this, it will at
least be non-ambiguous which box you're editing (e.g. once we determine
we're in the hitbox of one of the labels, we should ignore the rest).

**Comment by lukaswozniak** [comment]
The best user experience I can imagine would be to mouse scroll between overlapping annotations.

**Comment by lukaswozniak** [comment]
Also btw, I feel the changes from last commits was pretty significant. Could you make new release? For most users compiling the project with all those dependencies is a no go.

**Comment by jveitchmichaelis** [comment]
Yep, I'll push something later today.
