### ISSUE TITLE
Is there a binary for OS X available for download?

### ISSUE THREAD

**Issue by qizh** [jveitchmichaelis/deeplabel#3]
There's only windows one available in releases.

**Comment by jveitchmichaelis** [comment]
Heya apologies, I've not built it for os x in a while, I don't have a mac currently.

It will compile from source though, if you have homebrew the dependencies are straightforward to get.

**Comment by jveitchmichaelis** [comment]
Should be straight forward to deploy via Travis. I'll get on it :)

**Comment by jveitchmichaelis** [comment]
Fixed in https://github.com/jveitchmichaelis/deeplabel/commit/1e6cd74f680a1d3cacfc2db39f3aee318dbd28a7

New releases should automatically get Mac builds attached. @qizh Please check the latest [release](https://github.com/jveitchmichaelis/deeplabel/releases). If you have any trouble, let me know!
