### ISSUE TITLE
COCO Python API is expecting different labels

### ISSUE THREAD

**Issue by laibe** [jveitchmichaelis/deeplabel#4]
Hi @jveitchmichaelis thanks for your great work! 

I gave the experimental COCO export functionality a try and found that the [COCO Python API](https://github.com/cocodataset/cocoapi) is expecting high-level labels to be defined as `images` and `annotations`. Otherwise image ids are not loaded by the API. 

So I suggest changing

https://github.com/jveitchmichaelis/deeplabel/blob/2506147a751a936c5cef45dfe0678f73c48a5091/src/cocoexporter.cpp#L182-L183

to 

```cpp
label_file["images"] = image_array; 
label_file["annotations"] = annotations_array; 
```

**Comment by jveitchmichaelis** [comment]
Yep this sounds sensible, good catch. I've also seen multiple datasets that don't respect the standard (FLIR ADAS, for example), but I'd rather not be responsible for creating more ;)

http://cocodataset.org/#format-data

**Comment by jveitchmichaelis** [comment]
Should be fixed in https://github.com/jveitchmichaelis/deeplabel/commit/51d2c4cbaae34bd182d2a7dd6c95d96928060cf5, will wait for Travis to complete before closing.

**Comment by laibe** [comment]
perfect, thanks for the quick fix!

**Comment by jveitchmichaelis** [comment]
No worries. I have some other updates I'm working on before I upload a new binary, but let me know if you need one for Windows.
