### ISSUE TITLE
Issue in configure of object detector

### ISSUE THREAD

**Issue by absagargupta** [jveitchmichaelis/deeplabel#41]
Hello @jveitchmichaelis. 
So I was trying to run yolov4 pretrained model on some of my images. I ran into an issue.

So I made a new project as instructed. Then upload the image folder. While configuring the object detector with config,weight and names file, the OK (on which we are supposed to click) vanishes. Since I am not able to configure the object detector, I am not able to run inference on my images. 

Side note: I had earlier ran a yolov4-custom model on it with successful running. Whenever I try to configure the detector, the addresses of the weight,config and names of that project opens up. Changing the addresses makes the OK dissapear. 

I have no clue as to what is happening

**Comment by jveitchmichaelis** [comment]
Hi @absagargupta 

Sorry you've had trouble running your model in deeplabel. It's very difficult to debug this without more information. If you're able to share your weights and config info, privately if you need, I'd be happy to take a look for you.

You can email josh at restor.eco

Best

**Comment by absagargupta** [comment]
I shared them on the mail. I do not think that it is the issue of weights and config files. Basically it is doing so for all the model. Any change in address is doing the same. It is still showing me the previous coco.names that were added and not the new one.

**Comment by jveitchmichaelis** [comment]
Ah ok this is a different issue then. Does it work if you load this model first?

What do you mean by address?

I received your email so I'll take a look when I can, thanks!

**Comment by absagargupta** [comment]
![Screenshot from 2023-04-11 14-16-18](https://user-images.githubusercontent.com/45480422/231112434-879c7714-7532-4eea-9276-c8ccbd7957c5.png)
Paths to the model, config, names.

Yes it works if I load the first model. I think It is mainly because the coco.names of earler was with a single class whereas this one has 80 class. 
So is it possible that still the previous coco class is being considered ? Since even the terminal shows the class being added is a single one that too from previous project. 
$ ./deeplabel
Database structure looks good
QSqlDatabasePrivate::addDatabase: duplicate connection name '/media/sagar/New Volume4/everything/job/CNHi/auto-annotation/aaw', old connection removed.
Database structure looks good
Added detection class: 0 cotton

**Comment by jveitchmichaelis** [comment]
Yeah that sounds possible, probably it's not being cleared. Will have a look

**Comment by absagargupta** [comment]
Hello @jveitchmichaelis 
I found out the issue. It was that my config files and coco names were messed up. I am closing this issue. Sorry for any inconvienience.

**Comment by jveitchmichaelis** [comment]
I'll see if I can make the error reporting better here anyway, we shouldn't just close the dialogue.
