### ISSUE TITLE
Error:  QSqlError("", "Driver not loaded", "Driver not loaded")

### ISSUE THREAD

**Issue by Avagenzo** [jveitchmichaelis/deeplabel#5]
I was trying to get the exe file running under Windows 10, but the above error occured. Am I missing anything ?

**Comment by Avagenzo** [comment]
My bad. Found the explanation for windows: Once you've installed OpenCV...(!)

**Comment by jveitchmichaelis** [comment]
Not having OpenCV shouldn't give you that problem with QSql. Can you run the latest release OK? (these are provided with all the DLLs included).

https://github.com/jveitchmichaelis/deeplabel/releases

**Comment by Avagenzo** [comment]
Unfortunately no. It gives me the above error when i try to import images. The GUI work fine though

**Comment by jveitchmichaelis** [comment]
Ok, I'll label this as a bug for now. Can you try an older release, please? Maybe something's not been uploaded correctly in the latest one.

Maybe also check where you've saved the project database? Perhaps it's not writeable.

**Comment by Avagenzo** [comment]
It's all good. The error occurs when there is no project defined. Thank youfor the hint.

**Comment by jveitchmichaelis** [comment]
Definitely a bug that it lets you try to import images before a project is open... fixed. I've disabled the toolbar/menu items until a project is open. Will be in the next release.
